name: "Bug Report"
description: "Report a bug or issue with the project."

body:
  - type: textarea
    attributes:
      label: "Describe the Bug"
      placeholder: "Please provide a clear and concise description of the bug."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      placeholder: "1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error"
    validations:
      required: false
  
  - type: textarea
    attributes:
      label: "Expected Behavior"
      placeholder: "What was expected to happen?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual Behavior"
      placeholder: "What actually happened?"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Browser and OS Information"
      placeholder: 
        "- OS: [e.g. iOS]
        - Browser [e.g. chrome, safari]
        - Version [e.g. 22]
        -Device: [iPhone 16, Samsung Galaxy S23, etc.]"
    validations:
      required: false


  - type: textarea 
    attributes:
      label: "Additional Context"
      placeholder: "Screenshots or Other Relevant Information"
    validations:
      required: false
